import type { Metadata } from 'next'
import { Lato } from 'next/font/google'

import './globals.css'

const lato = Lato({ 
  weight: ['300', '400'],
  style: ['normal', 'italic'],
  subsets: ['latin'] 
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={lato.className}>{children}</body>
    </html>
  )
}
