export interface StatType {
    name: string;
    id: number;
    categories: {
        category: string;
        id: number;
        parksInCategory: string[];
    }[];
    collapsible: boolean;
}

export interface Section {
    header: string;
    id: string;
    color: string;
    parks: string[];
}

export interface Park {
    name: string;
    id: string;
    state: string;
    status: string;
    region: string;
    description: string;
    image: string;
}

export const parkData = [
    {
        'name': 'Bryce Canyon National Park',
        'id': '8',
        'state': 'Utah',
        'status': 'Completed',
        'region': 'Four Corners',
        'description': 'National park on the Paunsaugunt Plateau protecting a natural amphitheater of multicolored rock hoodoos.',
        'image': 'brycecanyonnp.jpg',
    },
            {
                'name': 'Carlsbad Caverns National Park',
                'id': '11',
                'state': 'New Mexico',
                'status': 'Completed',
                'region': 'Four Corners',
                'description': 'National park protecting a limestone cave with the largest subterranean chamber in North America.',
                'image': 'carlsbadcavernsnp.jpg',
            },
            {
                'name': 'Great Sand Dunes National Park',
                'id': '27',
                'state': 'Colorado',
                'status': 'Completed',
                'region': 'Four Corners',
                'description': 'National park bordering the Sangre de Cristo range protecting the tallest sand dunes in North America.',
                'image': 'greatsanddunesnp.jpg',
            },
            {
                'name': 'New River Gorge National Park',
                'id': '45',
                'state': 'West Virginia',
                'status': 'Completed',
                'region': 'Appalachians',
                'description': 'National park protecting the deepest river gorge east of the Mississippi.',
                'image': 'newrivergorgenp.jpg',
            },
            {
                'name': 'Petrified Forest National Park',
                'id': '48',
                'state': 'Arizona',
                'status': 'Completed',
                'region': 'Four Corners',
                'description': 'National park protecting one of the largest concentrations of petrified wood in the U.S. and the surrounding bentonite Painted Desert.',
                'image': 'petrifiedforestnp.jpg',
            },
            {
                'name': 'Saguaro National Park',
                'id': '52',
                'state': 'Arizona',
                'status': 'Completed',
                'region': 'Four Corners',
                'description': 'National park surrounding Tucson protecting the diverse ecosystem of the Sonoran Desert.',
                'image': 'saguaronp.jpg',
            },
            {
                'name': 'Sequoia National Park',
                'id': '53',
                'state': 'California',
                'status': 'Completed',
                'region': 'California, Nevada',
                'description': 'National park protecting sequoias (some of the largest trees in the world), caves, granite domes, and the tallest mountain in the contiguous U.S.',
                'image': 'sequoianp.jpg',
            },
            {
                'name': 'Wind Cave National Park',
                'id': '59',
                'state': 'South Dakota',
                'status': 'Completed',
                'region': 'Great Plains',
                'description': 'National park protecting both the mixed-grass prairie ecosystem aboveground and the boxwork of Wind Cave underground.',
                'image': 'windcavenp.jpg',
            },
            {
                'name': 'Arches National Park',
                'id': '3',
                'state': 'Utah',
                'status': 'Visited',
                'region': 'Four Corners',
                'description': 'National park on the Colorado Plateau protecting a large concentration of arches, including Delicate Arch and Landscape Arch.',
                'image': 'archesnp.jpg',
            },
            {
                'name': 'Badlands National Park',
                'id': '4',
                'state': 'South Dakota',
                'status': 'Visited',
                'region': 'Great Plains',
                'description': 'National park east of the Black Hills protecting patches of eroded badlands in the surrounding prairie.',
                'image': 'badlandsnp.jpg',
            },
            {
                'name': 'Canyonlands National Park',
                'id': '9',
                'state': 'Utah',
                'status': 'Visited',
                'region': 'Four Corners',
                'description': 'Very large national park on the Colorado Plateau protecting the canyons and mesas produced from the Colorado and Green Rivers.',
                'image': 'canyonlandsnp.jpg',
            },
            {
                'name': 'Crater Lake National Park',
                'id': '14',
                'state': 'Oregon',
                'status': 'Visited',
                'region': 'Pacific Northwest',
                'description': 'National park protecting Crater Lake, a lake produced from the eruption of an ancient stratovolcano and the deepest lake in the U.S.',
                'image': 'craterlakenp.jpg',
            },
            {
                'name': 'Death Valley National Park',
                'id': '16',
                'state': 'California',
                'status': 'Visited',
                'region': 'California, Nevada',
                'description': 'Sprawling national park protecting canyons, badlands, and dunes in the hottest, lowest, and driest place in the U.S.',
                'image': 'deathvalleynp.jpg',
            },
            {
                'name': 'Glacier National Park',
                'id': '22',
                'state': 'Montana',
                'status': 'Visited',
                'region': 'Yellowstone',
                'description': 'National park protecting glacial landforms on the border with Canada, including horns, aretes, and ribbon lakes',
                'image': 'glaciernp.jpg',
            },
            {
                'name': 'Grand Canyon National Park',
                'id': '24',
                'state': 'Arizona',
                'status': 'Visited',
                'region': 'Four Corners',
                'description': 'National park protecting the Grand Canyon, a massive canyon carved by the Colorado River over millions of years.',
                'image': 'grandcanyonnp.jpg',
            },
            {
                'name': 'Grand Teton National Park',
                'id': '25',
                'state': 'Wyoming',
                'status': 'Visited',
                'region': 'Yellowstone',
                'description': 'National park protecting the Teton Range and the adjacent piedmont lakes.',
                'image': 'grandtetonnp.jpg',
            },
            {
                'name': 'Great Basin National Park',
                'id': '26',
                'state': 'Nevada',
                'status': 'Visited',
                'region': 'California, Nevada',
                'description': 'National park protecting a cave system, rock glacier, groves of bristlecone pines, and dark skies surrounding Wheeler Peak.',
                'image': 'greatbasinnp.jpg',
            },
            {
                'name': 'Great Smoky Mountains National Park',
                'id': '28',
                'state': 'North Carolina/Tennessee',
                'status': 'Visited',
                'region': 'Appalachians',
                'description': 'National park on the border of North Carolina and Tennessee protecting the diversity and scenery of a section of the Appalachian mountains',
                'image': 'greatsmokymountainsnp.jpg',
            },
            {
                'name': 'Guadalupe Mountains National Park',
                'id': '29',
                'state': 'Texas',
                'status': 'Visited',
                'region': 'South',
                'description': 'National park protecting canyons, a fossilized coral reef, and the highest point in Texas, Guadalupe Peak.',
                'image': 'guadalupemountainsnp.jpg',
            },
            {
                'name': 'Joshua Tree National Park',
                'id': '35',
                'state': 'California',
                'status': 'Visited',
                'region': 'California, Nevada',
                'description': 'National park in the Colorado and Mojave Deserts protecting large numbers of Joshua trees and strange rock formations.',
                'image': 'joshuatreenp.jpg',
            },
            {
                'name': 'Kings Canyon National Park',
                'id': '38',
                'state': 'California',
                'status': 'Visited',
                'region': 'California, Nevada',
                'description': 'National park in the Sierra Nevada protecting the Kings Canyon and the sequoias around and including the General Grant tree.',
                'image': 'kingscanyonnp.jpg',
            },
            {
                'name': 'Lassen Volcanic National Park',
                'id': '41',
                'state': 'California',
                'status': 'Visited',
                'region': 'California, Nevada',
                'description': 'National park on the southern edge of the Cascades protecting volcanic activity around Lassen Peak, including examples of all four volcano types.',
                'image': 'lassenvolcanicnp.jpg',
            },
            {
                'name': 'Mammoth Cave National Park',
                'id': '42',
                'state': 'Kentucky',
                'status': 'Visited',
                'region': 'Appalachians',
                'description': 'National park protecting sinkholes, springs, and the longest cave system in the world.',
                'image': 'mammothcavenp.jpg',
            },
            {
                'name': 'Mount Rainier National Park',
                'id': '44',
                'state': 'Washington',
                'status': 'Visited',
                'region': 'Pacific Northwest',
                'description': 'National park protecting one of the most prominent and most glaciated peaks in the United States.',
                'image': 'mountrainiernp.jpg',
            },
            {
                'name': 'North Cascades National Park',
                'id': '46',
                'state': 'Washington',
                'status': 'Visited',
                'region': 'Pacific Northwest',
                'description': 'National park protecting the valleys, peaks, and ecosystem of the remote North Cascades range.',
                'image': 'northcascadesnp.jpg',
            },
            {
                'name': 'Olympic National Park',
                'id': '47',
                'state': 'Washington',
                'status': 'Visited',
                'region': 'Pacific Northwest',
                'description': 'Diverse national park protecting the glaciated Olympic Range, temperate rainforests, and sea stacks on the Pacific coast.',
                'image': 'olympicnp.jpg',
            },
            {
                'name': 'Pinnacles National Park',
                'id': '49',
                'state': 'California',
                'status': 'Visited',
                'region': 'California, Nevada',
                'description': 'National park protecting a collection of large andesite and rhyolite monoliths.',
                'image': 'pinnaclesnp.jpg',
            },
            {
                'name': 'Redwood National and State Parks',
                'id': '50',
                'state': 'California',
                'status': 'Visited',
                'region': 'California, Nevada',
                'description': 'National park protecting the tallest trees in the world, coastal redwoods, and the adjacent tide pools and sea stacks of the Pacific Coast.',
                'image': 'redwoodnp.jpg',
            },
            {
                'name': 'Rocky Mountain National Park',
                'id': '51',
                'state': 'Colorado',
                'status': 'Visited',
                'region': 'Four Corners',
                'description': 'National park protecting a portion of the Rocky Mountains defined by the Continental Divide.',
                'image': 'rockymountainnp.jpg',
            },
            {
                'name': 'Shenandoah National Park',
                'id': '54',
                'state': 'Virginia',
                'status': 'Visited',
                'region': 'Appalachians',
                'description': 'National park in the Blue Ridge Mountains protecting wildlife and waterfalls along the Shenandoah river.',
                'image': 'shenandoahnp.jpg',
            },
            {
                'name': 'Theodore Roosevelt National Park',
                'id': '55',
                'state': 'North Dakota',
                'status': 'Visited',
                'region': 'Great Plains',
                'description': 'National park with three units protecting badlands and wildlife in a region around Theodore Roosevelt\'s historic cabin.',
                'image': 'theodorerooseveltnp.jpg',
            },
            {
                'name': 'White Sands National Park',
                'id': '58',
                'state': 'New Mexico',
                'status': 'Visited',
                'region': 'Four Corners',
                'description': 'National park protecting the world\'s largest expanse of white gypsum dunes.',
                'image': 'whitesandsnp.jpg',
            },
            {
                'name': 'Yellowstone National Park',
                'id': '61',
                'state': 'Idaho/Montana/Wyoming',
                'status': 'Visited',
                'region': 'Yellowstone',
                'description': 'Large national park protecting canyons, lakes, and hydrothermal activity within the Yellowstone Caldera, a depression overlying the Yellowstone hotspot.',
                'image': 'yellowstonenp.jpg',
            },
            {
                'name': 'Yosemite National Park',
                'id': '62',
                'state': 'California',
                'status': 'Visited',
                'region': 'California, Nevada',
                'description': 'National park in the Sierra Nevada protecting the Yosemite valley, a glacially eroded scenic valley with steep walls and waterfalls.',
                'image': 'yosemitenp.jpg',
            },
            {
                'name': 'Zion National Park',
                'id': '63',
                'state': 'Utah',
                'status': 'Visited',
                'region': 'Four Corners',
                'description': 'National park protecting the canyons and mesas formed from the Virgin River.',
                'image': 'zionnp.jpg',
            },
            {
                'name': 'Acadia National Park',
                'id': '1',
                'state': 'Maine',
                'status': 'Not Completed',
                'region': 'Northeast',
                'description': 'National park on the Atlantic coast protecting granite cliffs and rocky coastline.',
                'image': 'acadianp.jpg',
            },
            {
                'name': 'National Park of American Samoa',
                'id': '2',
                'state': 'American Samoa',
                'status': 'Not Completed',
                'region': 'Other',
                'description': 'Remote national park in the Pacific Ocean protecting coral reefs and mountains around American Samoa.',
                'image': 'americansamoanp.jpg',
            },
            {
                'name': 'Big Bend National Park',
                'id': '5',
                'state': 'Texas',
                'status': 'Not Completed',
                'region': 'South',
                'description': 'National park in the Chihuahuan Desert protecting the Chisos Mountains and canyons along the Rio Grande.',
                'image': 'bigbendnp.jpg',
            },
            {
                'name': 'Biscayne National Park',
                'id': '6',
                'state': 'Florida',
                'status': 'Not Completed',
                'region': 'Southeast',
                'description': 'National park off the coast of Miami protecting coral reefs and a portion of the keys.',
                'image': 'biscaynenp.jpg',
            },
            {
                'name': 'Black Canyon of the Gunnison National Park',
                'id': '7',
                'state': 'Colorado',
                'status': 'Not Completed',
                'region': 'Four Corners',
                'description': 'National park protecting a dark, extremely steep canyon formed by the Gunnison River.',
                'image': 'blackcanyonnp.jpg',
            },
            {
                'name': 'Capitol Reef National Park',
                'id': '10',
                'state': 'Utah',
                'status': 'Not Completed',
                'region': 'Four Corners',
                'description': 'National park protecting the Waterpocket Fold, a nearly 100-mile monocline on the Colorado Plateau.',
                'image': 'capitolreefnp.jpg',
            },
            {
                'name': 'Channel Islands National Park',
                'id': '12',
                'state': 'California',
                'status': 'Not Completed',
                'region': 'California, Nevada',
                'description': 'National park protecting various islands off the coast of Los Angeles.',
                'image': 'channelislandsnp.jpg',
            },
            {
                'name': 'Congaree National Park',
                'id': '13',
                'state': 'South Carolina',
                'status': 'Not Completed',
                'region': 'Southeast',
                'description': 'National park protecting a floodplain on the Congaree River with some of the tallest trees in the eastern U.S.',
                'image': 'congareenp.jpg',
            },
            {
                'name': 'Cuyahoga Valley National Park',
                'id': '15',
                'state': 'Ohio',
                'status': 'Not Completed',
                'region': 'Midwest',
                'description': 'National park in Cleveland protecting the history and waterfalls along the Cuyahoga River.',
                'image': 'cuyahogavalleynp.jpg',
            },
            {
                'name': 'Denali National Park',
                'id': '17',
                'state': 'Alaska',
                'status': 'Not Completed',
                'region': 'Alaska',
                'description': 'National park in central Alaska protecting the tallest mountain in the contiguous U.S.',
                'image': 'denalinp.jpg',
            },
            {
                'name': 'Dry Tortugas National Park',
                'id': '18',
                'state': 'Florida',
                'status': 'Not Completed',
                'region': 'Southeast',
                'description': 'Remote national park west of the Florida Keys protecting Fort Jefferson and surrounding coral reefs.',
                'image': 'drytortugasnp.jpg',
            },
            {
                'name': 'Everglades National Park',
                'id': '19',
                'state': 'Florida',
                'status': 'Not Completed',
                'region': 'Southeast',
                'description': 'National park protecting the ecosystem of the Everglades, including crocodiles and manatees.',
                'image': 'evergladesnp.jpg',
            },
            {
                'name': 'Gates of the Arctic National Park',
                'id': '20',
                'state': 'Alaska',
                'status': 'Not Completed',
                'region': 'Alaska',
                'description': 'Very remote national park protecting a large portion of the Brooks Range north of the Arctic Circle.',
                'image': 'gatesofthearcticnp.jpg',
            },
            {
                'name': 'Gateway Arch National Park',
                'id': '21',
                'state': 'Missouri',
                'status': 'Not Completed',
                'region': 'Midwest',
                'description': 'National park protecting the Gateway Arch, a monument erected to commemorate the Lewis and Clark expedition.',
                'image': 'gatewayarchnp.jpg',
            },
            {
                'name': 'Glacier Bay National Park',
                'id': '23',
                'state': 'Alaska',
                'status': 'Not Completed',
                'region': 'Alaska',
                'description': 'National park protecting Glacier Bay, a region in the panhandle of Alaska containing tidewater glaciers and fjords.',
                'image': 'glacierbaynp.jpg',
            },
            {
                'name': 'Haleakala National Park',
                'id': '30',
                'state': 'Hawaii',
                'status': 'Not Completed',
                'region': 'Hawaii',
                'description': 'National park protecting the Haleakala crater, including its cinder cones and associated wildlife.',
                'image': 'haleakalanp.jpg',
            },
            {
                'name': 'Hawai\'i Volcanoes National Park',
                'id': '31',
                'state': 'Hawaii',
                'status': 'Not Completed',
                'region': 'Hawaii',
                'description': 'National park on the Big Island protecting some of the world\'s most active shield volcanoes, Kilauea and Mauna Loa.',
                'image': 'hawaiivolcanoesnp.jpg',
            },
            {
                'name': 'Hot Springs National Park',
                'id': '32',
                'state': 'Arkansas',
                'status': 'Not Completed',
                'region': 'South',
                'description': 'National park protecting the historical, recreational, and natural value of the hot springs flowing out of the Ouachita Mountains.',
                'image': 'hotspringsnp.jpg',
            },
            {
                'name': 'Indiana Dunes National Park',
                'id': '33',
                'state': 'Indiana',
                'status': 'Not Completed',
                'region': 'Midwest',
                'description': 'National park protecting a very biodiverse stretch of Lake Michigan lakeshore near Chicago.',
                'image': 'indianadunesnp.jpg',
            },
            {
                'name': 'Isle Royale National Park',
                'id': '34',
                'state': 'Michigan',
                'status': 'Not Completed',
                'region': 'Great Lakes',
                'description': 'Remote national park protecting Isle Royale, a secluded island in Lake Superior.',
                'image': 'isleroyalenp.jpg',
            },
            {
                'name': 'Katmai National Park',
                'id': '36',
                'state': 'Alaska',
                'status': 'Not Completed',
                'region': 'Alaska',
                'description': 'National park on the Alaska Peninsula protecting features such as Brooks Falls and the Valley of Ten Thousand Smokes.',
                'image': 'katmainp.jpg',
            },
            {
                'name': 'Kenai Fjords National Park',
                'id': '37',
                'state': 'Alaska',
                'status': 'Not Completed',
                'region': 'Alaska',
                'description': 'National park near Seward protecting glaciers and fjords on the Kenai Peninsula.',
                'image': 'kenaifjordsnp.jpg',
            },
            {
                'name': 'Kobuk Valley National Park',
                'id': '39',
                'state': 'Alaska',
                'status': 'Not Completed',
                'region': 'Alaska',
                'description': 'Remote national park protecting a stretch of the Kobuk River and a group of tall, arctic sand dunes.',
                'image': 'kobukvalleynp.jpg',
            },
            {
                'name': 'Lake Clark National Park',
                'id': '40',
                'state': 'Alaska',
                'status': 'Not Completed',
                'region': 'Alaska',
                'description': 'National park protecting active volcanoes, lakes, waterfalls, and mountains surrounding Lake Clark.',
                'image': 'lakeclarknp.jpg',
            },
            {
                'name': 'Mesa Verde National Park',
                'id': '43',
                'state': 'Colorado',
                'status': 'Not Completed',
                'region': 'Four Corners',
                'description': 'National park protecting ancient Puebloan cliff dwellings, including the massive Cliff Palace.',
                'image': 'mesaverdenp.jpg',
            },
            {
                'name': 'Virgin Islands National Park',
                'id': '56',
                'state': 'U.S. Virgin Islands',
                'status': 'Not Completed',
                'region': 'Other',
                'description': 'National park on Saint John in the U.S. Virgin Islands protecting beaches, coral reefs, and the remains of sugar plantations.',
                'image': 'virginislandsnp.jpg',
            },
            {
                'name': 'Voyageurs National Park',
                'id': '57',
                'state': 'Minnesota',
                'status': 'Not Completed',
                'region': 'Great Lakes',
                'description': 'National park on the border of Canada protecting a glacially influenced region formerly travelled by voyageurs, French fur traders.',
                'image': 'voyageursnp.jpg',
            },
            {
                'name': 'Wrangell-St. Elias National Park',
                'id': '60',
                'state': 'Alaska',
                'status': 'Not Completed',
                'region': 'Alaska',
                'description': 'The largest national park in the U.S., protecting various mountain ranges, large glaciers, and mining history.',
                'image': 'wrangellsteliasnp.jpg',
            },
]

export const typeData: StatType[] = [
    {
        'name': 'Status',
        'id': 1,
        'categories': [
            {
                'category': 'Completed',
                'id': 1,
                'parksInCategory': ['8', '11', '27', '45', '48', '52', '53', '59'],
            },
            {
                'category': 'Visited',
                'id': 2,
                'parksInCategory': ['3', '4', '9', '14', '16', '22', '24', '25', '26', '28', '29', '35', '38', '41', '42', '44', '46', '47', '49', '50', '51', '54', '55', '58', '61', '62', '63'],
            },
            {
                'category': 'Not Completed',
                'id': 3,
                'parksInCategory': ['1', '2', '5', '6', '7', '10', '12', '13', '15', '17', '18', '19', '20', '21', '23', '30', '31', '32', '33', '34', '36', '37', '39', '40', '43', '56', '57', '60'],
            },
        ],
        'collapsible': false,
    },
    {
        'name': 'Regions',
        'id': 2,
        'categories': [
            {
                'category': 'Pacific Northwest',
                'id': 1,
                'parksInCategory': ['14', '44', '46', '47'],
            },
            {
                'category': 'California, Nevada',
                'id': 2,
                'parksInCategory': ['53', '16', '26', '35', '38', '41', '49', '50', '62', '12'],
            },
            {
                'category': 'Yellowstone',
                'id': 3,
                'parksInCategory': ['22', '25', '61'],
            },
            {
                'category': 'Four Corners',
                'id': 4, 
                'parksInCategory': ['8', '11', '27', '48', '52', '3', '9', '24', '51', '58', '63', '7', '10', '43'],
            },
            {
                'category': 'Great Plains',
                'id': 5,
                'parksInCategory': ['59', '4', '55'],
            },
            {
                'category': 'Great Lakes',
                'id': 6,
                'parksInCategory': ['34', '57'],
            },
            {
                'category': 'Midwest',
                'id': 7,
                'parksInCategory': ['15', '21', '33'],
            },
            {
                'category': 'South',
                'id': 8,
                'parksInCategory': ['29', '5', '32'],
            },
            {
                'category': 'Southeast',
                'id': 9,
                'parksInCategory': ['6', '13', '18', '19'],
            },
            {
                'category': 'Appalachians',
                'id': 10,
                'parksInCategory': ['45', '28', '42', '54'],
            },
            {
                'category': 'Northeast',
                'id': 11,
                'parksInCategory': ['1'],
            },
            {
                'category': 'Alaska',
                'id': 12,
                'parksInCategory': ['17', '20', '23', '36', '37', '39', '40', '60'],
            },
            {
                'category': 'Hawaii',
                'id': 13,
                'parksInCategory': ['30', '31'],
            },
            {
                'category': 'Other',
                'id': 14,
                'parksInCategory': ['2' ,'56'],
            },
        ],
        'collapsible': true,
    }
]



export const sectionData = [
    {
        'header': 'Completed',
        'id': '1',
        'color': 'bg-bright-green',
        'parks': ['8', '11', '27', '45', '48', '52', '53', '59'],
    },
    {
        'header': 'Visited',
        'id': '2',
        'color': 'bg-bright-yellow',
        'parks': ['3', '4', '9', '14', '16', '22', '24', '25', '26', '28', '29', '35', '38', '41', '42', '44', '46', '47', '49', '50', '51', '54', '55', '58', '61', '62', '63'],
    },
    {
        'header': 'Not Completed',
        'id': '3',
        'color': 'bg-bright-red',
        'parks': ['1', '2', '5', '6', '7', '10', '12', '13', '15', '17', '18', '19', '20', '21', '23', '30', '31', '32', '33', '34', '36', '37', '39', '40', '43', '56', '57', '60'],
    },
]

